

POST http://localhost:3000/users
Content-Type : application/json

{
    "name" : "lakshmana",
    "mobileNumber" : "1234567892",
    "address" : "Ayodhya"
}

###

POST http://localhost:3000/posts
Content-Type : application/json

{
    "title" : "my second post",
    "description" : "playing vollyball",
    "userId" : 1,
    "images"  : ["https://res.cloudinary.com/dchkvmpzf/image/upload/v1680845932/cld-sample-3.jpg"]
}


###
GET http://localhost:3000/users
###

DELETE http://localhost:3000/users/2

GET http://localhost:3000/posts/
###

DELETE http://localhost:3000/posts/4
###

DELETE http://localhost:3000/posts/1/5
###


GET http://localhost:3000/users/posts
###


PUT http://localhost:3000/posts/1/5
Content-Type : application/json

{
    "images" : ["https://res.cloudinary.com/dchkvmpzf/image/upload/v1680845932/cld-sample-4.jpg"]
}
